---
# file: roles/corosync/tasks/auth.yml
- name: Deleting /etc/corosync/authkey
  file:
    path: '/etc/corosync/authkey'
    state: absent
  run_once: true
  when: corosync_force_regenerate_authkey is defined and
        corosync_force_regenerate_authkey

- name: Checking if /etc/corosync/authkey exists
  stat:
    path: '/etc/corosync/authkey'
  register: check_authkey_file

- name: Generating /etc/corosync/authkey file
  command:
    /usr/sbin/corosync-keygen
  run_once: true
  when: check_authkey_file.stat.exists == False

- name: Waiting for /etc/corosync/authkey file
  wait_for:
    path: '/etc/corosync/authkey'
    timeout: 30
  when: inventory_hostname == play_hosts[0]

- name: Fetching /etc/corosync/authkey
  slurp:
    src: '/etc/corosync/authkey'
    run_once: true
  register: tmp_authkey
  when: inventory_hostname == play_hosts[0]

- name: Synchronizing /etc/corosync/authkey everywhere
  copy:
    content: "{{ tmp_authkey['content'] | b64decode  }}"
    dest: /etc/corosync/authkey
    mode: 0400
  notify: restart corosync
  when: inventory_hostname not play_hosts[0]
