---
# file: roles/corosync/tasks/configuration.yml
- name: Configuring Corosync
  template:
    src=etc/corosync/corosync.conf.j2
    dest=/etc/corosync/corosync.conf
  notify: restart corosync

- name: Making sure that Corosync service is started
  service:
    name=corosync
    state=started

- meta: flush_handlers
